version: '3'
services:

  #php service
  web:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: web_tourism
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=tourism
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - ddd-network


  db:
    image: postgres:12.8-alpine
    container_name: db_tourism
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tourism
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./back/pgdata:/var/lib/postgresql/data
    networks:
      - ddd-network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 4200:4200
      - 80:80
    user: "1000:1000"
    container_name: app-front
    volumes:
       - ./front:/app
       - ./front/node_modules:/app/node_modules
    networks:
      - ddd-network

#Docker Networks
networks:
  ddd-network:
    driver: bridge

#Volumes
volumes:
  pgdata:
    driver: local