# Generated by Django 3.2.12 on 2023-05-04 14:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AlterField(
            model_name='site',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
    ]
